project_name: NengoLMU
pkg_name: lmu
repo_name: abr/lmu
description: Legendre Memory Units

copyright_start: 2019

license_rst: {}

contributing_rst: {}

contributors_rst: {}

manifest_in: {}

setup_py:
  python_requires: ">=3.6"
  install_req:
    - scipy
    - tensorflow>=2.1.0
  tests_req:
    - pytest>=6.1.0
    - pytest-rng>=1.0.0
  docs_req:
    - matplotlib>=3.0.2
    - jupyter>=1.0.0
    - seaborn>=0.9.0
    - sphinx>=1.8
    - nbsphinx>=0.3.5
    - nengo_sphinx_theme>=1.2.0
    - numpydoc>=0.6
  classifiers:
    - "Development Status :: 3 - Alpha"
    - "Framework :: Nengo"
    - "Intended Audience :: Science/Research"
    - "License :: Free for non-commercial use"
    - "Operating System :: OS Independent"
    - "Programming Language :: Python "
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Programming Language :: Python :: 3.8"
    - "Topic :: Scientific/Engineering "
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

setup_cfg: {}

docs_conf_py:
  intersphinx_mapping:
    scipy: "https://docs.scipy.org/doc/scipy/reference"
  tagmanager_id: GTM-KWCR2HN
  html_redirects:
    getting_started.html: getting-started.html
  autoautosummary_change_modules:
    lmu:
      - lmu.layers.LMUCell
      - lmu.layers.LMU
      - lmu.layers.LMUFFT
  extensions:
    - nengo_sphinx_theme.ext.autoautosummary
  doctest_setup:
    - import numpy as np
    - import tensorflow as tf

travis_yml:
  python: 3.8
  global_vars:
    TF_VERSION: tensorflow
  jobs:
    - script: static
    - script: test
    - script: test
      env:
        TF_VERSION: tensorflow==2.1.0
      python: 3.6
    - script: docs
    - script: examples
  pypi_user: arvoelke
  slack_notifications: "vv0lGEj/xNMFSZDbFsdoMJyEcr9BO8p43KUefmgHfjIQtodZqXdesLl+XJcXW\
    0jxCJlNyy3H8LHYP/mEGJpIsK+tQ7dxlWscLjSGWfcoNiZGy4a1Jp4fF+MZyYvIGlTRJqxrazIrj73tGF\
    ptVr2XDE74eO0Z9YaVSJVQw4twEDrWFEAq4foWxV30SkcXfdCkhBwX+43CJyuGE3YFDD/+03me/mdccjN\
    RqCfJ0lURRk7H5tcztryrZy2gpwHV+W73raGTybxlP1xEa1hyLYJO40eH/JfeqBqIDxa5m61Aw+BH/HJ5\
    ZLNlTEUyUB6p7kcIYO9lyko5TY3QSqlX9pK+tK+2DojDlzI97QwgQVbx4WvTJ1JEidfgRqNcTlJOG16Rv\
    lyxQjW1u3/QV67bmINus470qQqzIBbdLfM70v+E5Ga/bk+Gk1Z29btB7DxXt4z9dH9z3NXTOLhDpH5WZz\
    pcatrbfSrgMzKtxC+z6oLfDzzio9Fx20RiuHv3P8GtXyyR9WkelMH9GVi7xUBHVCveRVVhNKL555u7NbP\
    5TI6Jc9NZqf7OtrNsRKIY4MfGc9KKjYa+Ks+3PT+yQZ8u/ZMMddMTv73nzLH0pU715/CBl1hQGkKkopuk\
    GtKbCpdc666PnRrFy9l21hBqSNqLo/FGPF/Yqr+yTXhuhBhvNZnvFQU="
  deploy_dists:
    - sdist
    - bdist_wheel

ci_scripts:
  - template: static
  - template: docs
  - template: examples
  - template: test
    coverage: true
    pip_install:
      - $TF_VERSION
  - template: deploy

codecov_yml: {}

pre_commit_config_yaml: {}

pyproject_toml: {}
